plugins {
    id 'io.qameta.allure' version '4.3.0' apply false
}

allprojects {
    group = 'smartshop'
    version = '1.0-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

subprojects {
    tasks.withType(Test).configureEach {
        useJUnitPlatform()

        System.properties.each { key, value ->
            if (key.toString().startsWith('smartshop.')) {
                systemProperty key.toString(), value
            }
        }
    }
}

tasks.register('apiSmoke') {
    group = 'verification'
    description = 'Запускает smoke API-тесты'
    dependsOn ':api-tests:apiSmoke'
}

tasks.register('uiSmoke') {
    group = 'verification'
    description = 'Запускает smoke UI-тесты'
    dependsOn ':ui-tests:uiSmoke'
}

tasks.register('smoke') {
    group = 'verification'
    description = 'Запускает smoke API- и UI-тесты'
    dependsOn 'apiSmoke', 'uiSmoke'
}
